### ISSUE TITLE
No Ambient Reload?

### ISSUE THREAD

**Issue by Morgandri1** [TheRhet0rical/r5goldmags#1]
there's no ambient reload, so I figure ill try and make it work yknow?

I dunno this probs won't work

does anyone have some gold heavy mag code lying around?

**Comment by TheRhet0rical** [comment]
Thanks for letting me know of the issue, but I plan to release the updated version today. This includes energy and heavy mags, but I am still working on ambient reloads. If you have any recommendations lying around, I'll take them. Thanks.

**Comment by TheRhet0rical** [comment]
I Will Leave This Open Just In Case You Have Any Input :)

**Comment by Morgandri1** [comment]
sorry, I meant to say that because this is listed as open-source, I would try to patch in ambient reloading. 

sorry for any confusion caused.

**Comment by TheRhet0rical** [comment]
Oh no it's okay! I didn't realize it was listed open source (I don't even know how to change it) Tbh i would really like it if you could tell me how! Seems like something messed up on both of our parts.
